name: Firmware on Windows

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          install: >-
            dosfstools
            git
            mingw-w64-x86_64-arm-none-eabi-gcc
            make
            gcc
            bc
            mingw-w64-x86_64-mtools

      - uses: actions/checkout@v6

      - name: Checkout Submodules
        run: |
          git submodule update --init --depth=1 firmware/ChibiOS
          git submodule update --init --depth=1 firmware/ChibiOS-Contrib
          git submodule update --init --depth=1 firmware/libfirmware
          git submodule update --init --depth=1 firmware/ext/lua
          git submodule update --init --depth=1 firmware/ext/uzlib
          git submodule update --init --depth=1 firmware/ext/openblt
          git submodule update --init --depth=1 firmware/controllers/lua/luaaa
          git submodule update --init --depth=1 firmware/controllers/can/wideband_firmware
          git submodule update --init --depth=1 java_console/luaformatter
          git submodule update --init --depth=1 java_console/peak-can-basic
          git submodule update --init --depth=1 misc/hex2dfu

      - name: Print bash version
        run: bash --version

      - name: Test Java Compiler
        run: |
          export PATH="$(cygpath -u "$JAVA_HOME")/bin:$PATH"
          javac -version

      - name: Print arm GCC version
        run: arm-none-eabi-gcc -v

      - name: Print make version
        run: make -v

      - name: Compile Firmware
        working-directory: firmware
        run: |
          export PATH="$(cygpath -u "$JAVA_HOME")/bin:$PATH"
          make -j4
